language: erlang

otp_release:
  - 21.3
  - 20.3
  - 19.3

install:
    pip install --user --disable-pip-version-check codecov

script:
  - rebar3 compile
  - rebar3 eunit --cover
  - rebar3 proper --cover
  - rebar3 ct --cover --readable=false
  - rebar3 cover
  - rebar3 codecov analyze

after_success:
    codecov
